### ISSUE TITLE
Try running on 3 channels images, requires too much memory?

### ISSUE THREAD

**Issue by jinglescode** [hula-ai/capsule_network_dynamic_routing#1]
Thanks for contributing, I saw your comments on https://github.com/gram-ai/capsule-networks/issues, and gave it a try. 

Instead of testing on Mnist, I am tried it on Cifar10. I do not have weights mismatch, but seems like it requires a lot of memory? I have reduced batch_size to 16.

`RuntimeError: CUDA out of memory. Tried to allocate 26.41 GiB (GPU 0; 11.17 GiB total capacity; 3.16 GiB already allocated; 6.24 GiB free; 1.45 GiB cached)`

Have you tried running it on Cifar10 or Imagenet?

This is my notebook:
https://colab.research.google.com/drive/1QLA6ktgjJlN-mtfm3VUBJ38VLPAXkD4q

**Comment by amobiny** [comment]
Hey there,
Thanks for giving it a shot.
I looked at your code and I think it is because you are resizing your images to 224 (            transforms.RandomResizedCrop(224)). If you change 224 to 28 (or some other reasonable size), it works with no problem. Even if you want to try capsule network on larger images, I'd say use some convolutions (with s>1) or even some pre-trained networks (e.g. use them as feature extractors; use the output of the last convolution to create the primary caps) to make the spatial dimensions (height and width) smaller before creating the primary capsules. The OOM problem happens in dynamic routing when you have a lot of capsules.

**Comment by amobiny** [comment]
I also added the CIFAR10 dataset. You may, however, do a search and find the best capsnet architecture by changing the hyperparameters
